name: Add labels to stale issues
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          days-before-issue-stale: 180
          days-before-pr-stale: -1
          days-before-issue-close: -1
          days-before-pr-close: -1
          stale-issue-label: "stale"
          operations-per-run: 300
          stale-issue-message: "There hasn't been any discussion on this issue for a while, so we're marking it as stale. If you choose to kick off the discussion again, we'll remove the 'stale' label."
          stale-pr-message: "Message to comment on stale PRs. If none provided, will not mark PRs stale"
